//
//  EntityDossier.swift
//  Kalsmritikosh
//
//  Build a Markdown "dossier" for a canonical entity: a single
//  document that pulls together every mention across the archive,
//  every event the entity participates in, every alias the ledger
//  collapsed onto it, and a per-source citation list. Useful as a
//  shareable artifact ("everything the system knows about X") and
//  as a sanity check for entity-resolution quality.
//

import Foundation

public nonisolated enum EntityDossier {

    /// Pulls the three sources the dossier needs from the existing
    /// repositories, then hands the gathered data to `render(...)`.
    /// Returns nil when no entity matches the id.
    public static func build(
        forEntityID id: Entity.ID,
        entities: EntitiesRepository,
        events: EventsRepository,
        objects: KnowledgeObjectRepository,
        mentionLimit: Int = 500
    ) async throws -> String? {
        guard let canonical = try await entities.find(byID: id) else { return nil }
        let mentions = try await entities.mentions(forEntityID: id, limit: mentionLimit)
        let recentEvents = try await events.recent(limit: 1_000)
        let participatesIn = recentEvents.filter { $0.entityIDs.contains(id) }
        return render(
            entity: canonical,
            mentions: mentions,
            events: participatesIn
        )
    }

    /// Pure-function renderer split from `build` so it's trivially
    /// testable with hand-rolled inputs.
    public static func render(
        entity: Entity,
        mentions: [EntityMentionRow],
        events: [Event]
    ) -> String {
        var out: [String] = []
        out.append("# Dossier: \(entity.value)")
        out.append("")
        // Legal / accuracy declaration on every exported dossier.
        out.append(LegalNotice.reportDisclaimer)
        out.append("")
        out.append("- **Kind:** \(entity.kind.rawValue)")
        if let normalized = entity.normalizedValue, normalized != entity.value {
            out.append("- **Normalized:** `\(normalized)`")
        }
        out.append("- **Confidence:** \(formatConfidence(entity.confidence))")
        out.append("- **Mentions:** \(mentions.count)")
        out.append("- **Events:** \(events.count)")
        out.append("")

        // Surface forms — collapses every distinct way the entity
        // showed up across the corpus. Helps the user spot wrong
        // merges ("Kalsmritikosh LLC" + "KalsmritikoshCorp" both folded into one).
        let surfaces = surfaceForms(in: mentions)
        if !surfaces.isEmpty {
            out.append("## Surface forms")
            out.append("")
            for (form, count) in surfaces {
                out.append("- `\(form)` × \(count)")
            }
            out.append("")
        }

        // Mentions by source file — one bullet per file rather than
        // per row, so a 50-message PST thread doesn't drown the
        // dossier. Mentioning files are listed newest first.
        if !mentions.isEmpty {
            out.append("## Sources")
            out.append("")
            let grouped = groupByFile(mentions)
            for group in grouped {
                let dateString = group.newest.formatted(date: .abbreviated, time: .omitted)
                out.append("- **\(group.file.lastPathComponent)** (\(group.type.rawValue), \(group.count) mention\(group.count == 1 ? "" : "s"), newest \(dateString))")
            }
            out.append("")
        }

        // Events the entity participates in, sorted chronologically.
        if !events.isEmpty {
            out.append("## Events")
            out.append("")
            let sorted: [Event] = events.sorted { (a: Event, b: Event) -> Bool in a.date < b.date }
            for event in sorted {
                let date = event.date.formatted(date: .abbreviated, time: .omitted)
                let summary = (event.summary ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
                let titleLine = event.title.isEmpty ? "(untitled event)" : event.title
                if summary.isEmpty {
                    out.append("- `\(date)` — \(titleLine)")
                } else {
                    out.append("- `\(date)` — \(titleLine): \(summary)")
                }
            }
            out.append("")
        }

        out.append("---")
        out.append("")
        out.append("Generated by Kalsmritikosh · \(Date().formatted(date: .abbreviated, time: .shortened))")
        return out.joined(separator: "\n")
    }

    // MARK: - Helpers

    private static func formatConfidence(_ c: Confidence) -> String {
        switch c.value {
        case 0.7...: return "high (\(String(format: "%.2f", c.value)))"
        case 0.4..<0.7: return "medium (\(String(format: "%.2f", c.value)))"
        default: return "low (\(String(format: "%.2f", c.value)))"
        }
    }

    private static func surfaceForms(in mentions: [EntityMentionRow]) -> [(String, Int)] {
        var counts: [String: Int] = [:]
        for m in mentions {
            let form = m.surface.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !form.isEmpty else { continue }
            counts[form, default: 0] += 1
        }
        return counts.sorted { $0.value > $1.value }
    }

    private struct FileGroup {
        let file: URL
        let type: SourceType
        let count: Int
        let newest: Date
    }

    private static func groupByFile(_ mentions: [EntityMentionRow]) -> [FileGroup] {
        var byFile: [URL: (type: SourceType, count: Int, newest: Date)] = [:]
        for m in mentions {
            let prior = byFile[m.sourceFile]
            byFile[m.sourceFile] = (
                type: m.sourceType,
                count: (prior?.count ?? 0) + 1,
                newest: max(prior?.newest ?? .distantPast, m.createdAt)
            )
        }
        return byFile
            .map { FileGroup(file: $0.key, type: $0.value.type, count: $0.value.count, newest: $0.value.newest) }
            .sorted { $0.newest > $1.newest }
    }
}
