//
//  JobDocumentationGenerated.swift
//  Kalsmritikosh
//
//  GENERATED — do not hand-edit. Source of truth:
//  PERSONA_JOB_COVERAGE_MATRIX.csv. Regenerate with
//  scripts/generate-job-docs.sh; JobDocumentationDriftTests enforces parity.
//

import Foundation

enum JobDocumentationGenerated {
    nonisolated static let all: [JobDocumentation] = [
        JobDocumentation(
            jobID: "INV-01",
            persona: "Investigator",
            name: "Case intake & scope",
            workflow: "Create case; define mandate; set scope/date bounds",
            requiredInputs: ["Mandate text", "scope", "sources", "date range"],
            methods: ["intake", "scope"],
            workProducts: ["Investigation Plan"],
            humanDecisions: ["Confirm scope"],
            prohibitedConclusions: ["Decide case merits"]),
        JobDocumentation(
            jobID: "INV-02",
            persona: "Investigator",
            name: "Subject workup",
            workflow: "Assemble everything known about a subject",
            requiredInputs: ["Subject identity", "sources"],
            methods: ["select evidence", "review"],
            workProducts: ["Subject Dossier"],
            humanDecisions: ["Confirm subject identity"],
            prohibitedConclusions: ["Assert guilt"]),
        JobDocumentation(
            jobID: "INV-03",
            persona: "Investigator",
            name: "Identity resolution",
            workflow: "Resolve aliases/identifiers to one canonical subject",
            requiredInputs: ["Candidate identifiers", "mentions"],
            methods: ["review evidence", "decision"],
            workProducts: ["Identity Resolution Decision log"],
            humanDecisions: ["Confirm/reject merge"],
            prohibitedConclusions: ["Auto-merge without review"]),
        JobDocumentation(
            jobID: "INV-04",
            persona: "Investigator",
            name: "Brainstorm board",
            workflow: "Capture ideas/hypotheses/leads as typed proposals",
            requiredInputs: ["Case context"],
            methods: ["brainstorm"],
            workProducts: ["Brainstorm export"],
            humanDecisions: ["Promote proposal to hypothesis"],
            prohibitedConclusions: ["Treat idea as fact"]),
        JobDocumentation(
            jobID: "INV-05",
            persona: "Investigator",
            name: "5W1H worksheet",
            workflow: "Answer who/what/when/where/why/how from evidence",
            requiredInputs: ["Sources", "Claims"],
            methods: ["5W1H", "select evidence"],
            workProducts: ["5W1H Worksheet"],
            humanDecisions: ["Confirm each cell"],
            prohibitedConclusions: ["Fabricate unknown W"]),
        JobDocumentation(
            jobID: "INV-06",
            persona: "Investigator",
            name: "Evidence collection plan",
            workflow: "Plan what evidence to gather for each hypothesis",
            requiredInputs: ["Hypotheses", "gaps"],
            methods: ["gap analysis", "form"],
            workProducts: ["Evidence Collection Plan"],
            humanDecisions: ["Confirm requests"],
            prohibitedConclusions: ["Assert evidence exists"]),
        JobDocumentation(
            jobID: "INV-07",
            persona: "Investigator",
            name: "Hypothesis matrix",
            workflow: "Score hypotheses against evidence for/against",
            requiredInputs: ["Hypotheses", "evidence"],
            methods: ["hypothesis matrix", "review"],
            workProducts: ["Hypothesis Matrix"],
            humanDecisions: ["Confirm/reject hypothesis"],
            prohibitedConclusions: ["Pick winner autonomously"]),
        JobDocumentation(
            jobID: "INV-08",
            persona: "Investigator",
            name: "Source reliability",
            workflow: "Assess reliability of each source/custodian",
            requiredInputs: ["Sources", "custody"],
            methods: ["review evidence", "matrix"],
            workProducts: ["Source Reliability Schedule"],
            humanDecisions: ["Confirm reliability rating"],
            prohibitedConclusions: ["Auto-rate as fact"]),
        JobDocumentation(
            jobID: "INV-09",
            persona: "Investigator",
            name: "Investigation timeline",
            workflow: "Build cited chronology of events",
            requiredInputs: ["Events", "dates"],
            methods: ["timeline analysis"],
            workProducts: ["Chronology"],
            humanDecisions: ["Confirm inclusion"],
            prohibitedConclusions: ["Invent dates"]),
        JobDocumentation(
            jobID: "INV-10",
            persona: "Investigator",
            name: "Relationship graph",
            workflow: "Map evidence-backed relationships",
            requiredInputs: ["Entities", "relationships"],
            methods: ["relationship analysis", "graph"],
            workProducts: ["Relationship Report"],
            humanDecisions: ["Confirm edges"],
            prohibitedConclusions: ["Assert relationship w/o evidence"]),
        JobDocumentation(
            jobID: "INV-11",
            persona: "Investigator",
            name: "Transaction & asset flow",
            workflow: "Trace transactions/assets across sources",
            requiredInputs: ["Transactions", "amounts"],
            methods: ["transaction flow", "calculation"],
            workProducts: ["Transaction/Asset Flow"],
            humanDecisions: ["Confirm flow"],
            prohibitedConclusions: ["Conclude fraud"]),
        JobDocumentation(
            jobID: "INV-12",
            persona: "Investigator",
            name: "Contradiction & gap desk",
            workflow: "Review contradictions and missing evidence in scope",
            requiredInputs: ["Claims", "contradictions", "gaps"],
            methods: ["contradiction matrix", "gap analysis"],
            workProducts: ["Contradiction Schedule", "Missing-Evidence Register"],
            humanDecisions: ["Confirm/dismiss"],
            prohibitedConclusions: ["Average conflicting accounts"]),
        JobDocumentation(
            jobID: "INV-13",
            persona: "Investigator",
            name: "Five Whys",
            workflow: "Trace causal chain with evidence at each level",
            requiredInputs: ["Problem statement", "evidence"],
            methods: ["five whys", "review"],
            workProducts: ["Five-Whys Analysis"],
            humanDecisions: ["Confirm each Why"],
            prohibitedConclusions: ["Force five levels w/o evidence"]),
        JobDocumentation(
            jobID: "INV-14",
            persona: "Investigator",
            name: "Fishbone",
            workflow: "Categorize candidate causes by branch",
            requiredInputs: ["Problem", "evidence"],
            methods: ["fishbone", "brainstorm"],
            workProducts: ["Fishbone Analysis"],
            humanDecisions: ["Confirm relevance"],
            prohibitedConclusions: ["Call a bone the root cause"]),
        JobDocumentation(
            jobID: "INV-15",
            persona: "Investigator",
            name: "Root-cause assessment",
            workflow: "Weigh candidate causes; record human determination",
            requiredInputs: ["Candidate causes", "evidence"],
            methods: ["root-cause assessment", "human approval"],
            workProducts: ["Root-Cause Assessment"],
            humanDecisions: ["Human root-cause decision"],
            prohibitedConclusions: ["App confirms root cause"]),
        JobDocumentation(
            jobID: "INV-16",
            persona: "Investigator",
            name: "CAPA register",
            workflow: "Record corrective/preventive actions linked to causes",
            requiredInputs: ["Confirmed/candidate causes"],
            methods: ["capa", "form"],
            workProducts: ["CAPA Register"],
            humanDecisions: ["Confirm owner/due/action"],
            prohibitedConclusions: ["Close CAPA autonomously"]),
        JobDocumentation(
            jobID: "INV-17",
            persona: "Investigator",
            name: "Effectiveness review",
            workflow: "Verify CAPA effectiveness with evidence",
            requiredInputs: ["CAPA actions", "new evidence"],
            methods: ["effectiveness review"],
            workProducts: ["Effectiveness Review"],
            humanDecisions: ["Confirm effectiveness"],
            prohibitedConclusions: ["Declare effective w/o evidence"]),
        JobDocumentation(
            jobID: "INV-18",
            persona: "Investigator",
            name: "Chain of custody",
            workflow: "Maintain custody chain for exhibits",
            requiredInputs: ["Sources", "custody events"],
            methods: ["review", "form"],
            workProducts: ["Evidence/Custody Manifest"],
            humanDecisions: ["Confirm custody entries"],
            prohibitedConclusions: ["Break custody silently"]),
        JobDocumentation(
            jobID: "INV-19",
            persona: "Investigator",
            name: "Investigation findings",
            workflow: "Produce cited findings report",
            requiredInputs: ["Selected Claims", "scope"],
            methods: ["work-product build"],
            workProducts: ["Investigation Findings"],
            humanDecisions: ["Approve report"],
            prohibitedConclusions: ["Assert unproven findings"]),
        JobDocumentation(
            jobID: "INV-20",
            persona: "Investigator",
            name: "Closure & export",
            workflow: "Close case; export report + receipt",
            requiredInputs: ["Findings", "approvals"],
            methods: ["closure", "work-product build"],
            workProducts: ["Closure Report", "sealed receipt"],
            humanDecisions: ["Human closure decision"],
            prohibitedConclusions: ["Close w/o human decision"]),
        JobDocumentation(
            jobID: "RES-01",
            persona: "Researcher",
            name: "Research protocol",
            workflow: "Define question; scope; method plan",
            requiredInputs: ["Question", "corpus", "scope"],
            methods: ["intake", "scope"],
            workProducts: ["Research Protocol"],
            humanDecisions: ["Confirm protocol"],
            prohibitedConclusions: ["Decide findings"]),
        JobDocumentation(
            jobID: "RES-02",
            persona: "Researcher",
            name: "Corpus catalogue",
            workflow: "Catalogue every source with provenance",
            requiredInputs: ["Sources"],
            methods: ["form", "table"],
            workProducts: ["Corpus Catalogue"],
            humanDecisions: ["Confirm inclusion"],
            prohibitedConclusions: ["Assert authenticity"]),
        JobDocumentation(
            jobID: "RES-03",
            persona: "Researcher",
            name: "Metadata & finding aid",
            workflow: "Record structured metadata per source",
            requiredInputs: ["Sources"],
            methods: ["form"],
            workProducts: ["Metadata export"],
            humanDecisions: ["Confirm metadata"],
            prohibitedConclusions: ["Invent metadata"]),
        JobDocumentation(
            jobID: "RES-04",
            persona: "Researcher",
            name: "Transcription & coding",
            workflow: "Transcribe/correct source text with locators",
            requiredInputs: ["Audio/image sources"],
            methods: ["transcription", "review"],
            workProducts: ["Corrected transcript"],
            humanDecisions: ["Confirm corrections"],
            prohibitedConclusions: ["Assert unheard words"]),
        JobDocumentation(
            jobID: "RES-05",
            persona: "Researcher",
            name: "Authority control",
            workflow: "Unify names/terms to canonical authorities",
            requiredInputs: ["Entities", "aliases"],
            methods: ["review", "decision"],
            workProducts: ["Authority file"],
            humanDecisions: ["Confirm authority"],
            prohibitedConclusions: ["Auto-unify w/o review"]),
        JobDocumentation(
            jobID: "RES-06",
            persona: "Researcher",
            name: "Source criticism",
            workflow: "Assess origin/bias/reliability of sources",
            requiredInputs: ["Sources"],
            methods: ["source criticism", "review"],
            workProducts: ["Source Criticism notes"],
            humanDecisions: ["Confirm assessment"],
            prohibitedConclusions: ["Declare truth from one source"]),
        JobDocumentation(
            jobID: "RES-07",
            persona: "Researcher",
            name: "Screening (include / exclude)",
            workflow: "Screen documents in/out by criteria",
            requiredInputs: ["Corpus", "criteria"],
            methods: ["form", "table"],
            workProducts: ["Screening log"],
            humanDecisions: ["Confirm screening"],
            prohibitedConclusions: ["Auto-exclude silently"]),
        JobDocumentation(
            jobID: "RES-08",
            persona: "Researcher",
            name: "Extraction & coding",
            workflow: "Code passages into structured findings",
            requiredInputs: ["Sources", "codebook"],
            methods: ["form", "matrix"],
            workProducts: ["Coded dataset"],
            humanDecisions: ["Confirm codes"],
            prohibitedConclusions: ["Fabricate coded content"]),
        JobDocumentation(
            jobID: "RES-09",
            persona: "Researcher",
            name: "Chronology & periodisation",
            workflow: "Build periodised timeline",
            requiredInputs: ["Events", "dates"],
            methods: ["timeline analysis"],
            workProducts: ["Chronology"],
            humanDecisions: ["Confirm periods"],
            prohibitedConclusions: ["Invent dates/periods"]),
        JobDocumentation(
            jobID: "RES-10",
            persona: "Researcher",
            name: "Prosopography",
            workflow: "Compile collective biography of a group",
            requiredInputs: ["Entities", "events"],
            methods: ["relationship analysis", "table"],
            workProducts: ["Prosopography table"],
            humanDecisions: ["Confirm entries"],
            prohibitedConclusions: ["Assert unknown biography"]),
        JobDocumentation(
            jobID: "RES-11",
            persona: "Researcher",
            name: "Interpretation comparison",
            workflow: "Compare competing interpretations with evidence",
            requiredInputs: ["Claims", "interpretations"],
            methods: ["contradiction matrix", "review"],
            workProducts: ["Interpretation comparison"],
            humanDecisions: ["Confirm interpretation"],
            prohibitedConclusions: ["Pick a winner"]),
        JobDocumentation(
            jobID: "RES-12",
            persona: "Researcher",
            name: "Alternative histories",
            workflow: "Explore evidence-bounded counterfactuals",
            requiredInputs: ["Events", "causal links"],
            methods: ["timeline analysis", "scenario"],
            workProducts: ["Alternative-history note"],
            humanDecisions: ["Confirm scenario scope"],
            prohibitedConclusions: ["Present scenario as fact"]),
        JobDocumentation(
            jobID: "RES-13",
            persona: "Researcher",
            name: "Bibliography & citation audit",
            workflow: "Verify citations resolve to sources",
            requiredInputs: ["Citations", "sources"],
            methods: ["review", "form"],
            workProducts: ["Bibliography", "citation audit"],
            humanDecisions: ["Confirm citations"],
            prohibitedConclusions: ["Assert unresolved cite"]),
        JobDocumentation(
            jobID: "RES-14",
            persona: "Researcher",
            name: "Annotated edition",
            workflow: "Assemble annotated edition/export",
            requiredInputs: ["Selected sources", "notes"],
            methods: ["work-product build"],
            workProducts: ["Annotated edition", "receipt"],
            humanDecisions: ["Approve edition"],
            prohibitedConclusions: ["Alter source text silently"]),
        JobDocumentation(
            jobID: "JRN-01",
            persona: "Journalist",
            name: "Story intake",
            workflow: "Frame story; scope; sources",
            requiredInputs: ["Story premise", "scope", "sources"],
            methods: ["intake", "scope"],
            workProducts: ["Story brief"],
            humanDecisions: ["Confirm premise"],
            prohibitedConclusions: ["Decide truth of story"]),
        JobDocumentation(
            jobID: "JRN-02",
            persona: "Journalist",
            name: "Fact-check board",
            workflow: "Track each story claim + support",
            requiredInputs: ["Claims", "sources"],
            methods: ["matrix", "review"],
            workProducts: ["Claim board export"],
            humanDecisions: ["Confirm claim status"],
            prohibitedConclusions: ["Publish unverified claim"]),
        JobDocumentation(
            jobID: "JRN-03",
            persona: "Journalist",
            name: "Source map",
            workflow: "Map sources and what each supports",
            requiredInputs: ["Sources", "Claims"],
            methods: ["graph", "relationship analysis"],
            workProducts: ["Source map"],
            humanDecisions: ["Confirm links"],
            prohibitedConclusions: ["Expose confidential source"]),
        JobDocumentation(
            jobID: "JRN-04",
            persona: "Journalist",
            name: "Source reliability",
            workflow: "Rate source reliability/independence",
            requiredInputs: ["Sources"],
            methods: ["source criticism", "review"],
            workProducts: ["Source reliability schedule"],
            humanDecisions: ["Confirm rating"],
            prohibitedConclusions: ["Auto-rate as fact"]),
        JobDocumentation(
            jobID: "JRN-05",
            persona: "Journalist",
            name: "Interview plan",
            workflow: "Plan interviews/questions from gaps",
            requiredInputs: ["Gaps", "Claims"],
            methods: ["gap analysis", "form"],
            workProducts: ["Interview plan"],
            humanDecisions: ["Confirm questions"],
            prohibitedConclusions: ["Assert answers"]),
        JobDocumentation(
            jobID: "JRN-06",
            persona: "Journalist",
            name: "Quote book",
            workflow: "Collect quotations with exact locators",
            requiredInputs: ["Sources", "transcripts"],
            methods: ["select evidence", "review"],
            workProducts: ["Quote book"],
            humanDecisions: ["Confirm quote/context"],
            prohibitedConclusions: ["Alter a quote"]),
        JobDocumentation(
            jobID: "JRN-07",
            persona: "Journalist",
            name: "Transcript correction",
            workflow: "Correct transcripts preserving provenance",
            requiredInputs: ["Audio/transcripts"],
            methods: ["transcription", "review"],
            workProducts: ["Corrected transcript"],
            humanDecisions: ["Confirm corrections"],
            prohibitedConclusions: ["Invent speech"]),
        JobDocumentation(
            jobID: "JRN-08",
            persona: "Journalist",
            name: "Tick-tock (timeline)",
            workflow: "Build cited story timeline",
            requiredInputs: ["Events", "dates"],
            methods: ["timeline analysis"],
            workProducts: ["Chronology"],
            humanDecisions: ["Confirm inclusion"],
            prohibitedConclusions: ["Invent dates"]),
        JobDocumentation(
            jobID: "JRN-09",
            persona: "Journalist",
            name: "Fact verification",
            workflow: "Verify each claim against evidence",
            requiredInputs: ["Claims", "evidence"],
            methods: ["review", "contradiction matrix"],
            workProducts: ["Verification log"],
            humanDecisions: ["Confirm verification"],
            prohibitedConclusions: ["Mark verified w/o evidence"]),
        JobDocumentation(
            jobID: "JRN-10",
            persona: "Journalist",
            name: "Open questions",
            workflow: "Track what is not yet known",
            requiredInputs: ["Gaps"],
            methods: ["gap analysis"],
            workProducts: ["Reporting-gap register"],
            humanDecisions: ["Confirm gaps"],
            prohibitedConclusions: ["Imply wrongdoing from absence"]),
        JobDocumentation(
            jobID: "JRN-11",
            persona: "Journalist",
            name: "Right of reply",
            workflow: "Track responses/denials from subjects",
            requiredInputs: ["Correspondence", "Claims"],
            methods: ["form", "review"],
            workProducts: ["Right-of-reply log"],
            humanDecisions: ["Confirm responses"],
            prohibitedConclusions: ["Omit a reply silently"]),
        JobDocumentation(
            jobID: "JRN-12",
            persona: "Journalist",
            name: "Publication decision",
            workflow: "Record human go/no-go with rationale",
            requiredInputs: ["Verification", "legal review"],
            methods: ["decision", "human approval"],
            workProducts: ["Publication decision record"],
            humanDecisions: ["Human publication decision"],
            prohibitedConclusions: ["App approves publication"]),
        JobDocumentation(
            jobID: "JRN-13",
            persona: "Journalist",
            name: "Correction history",
            workflow: "Track post-publication corrections",
            requiredInputs: ["Published items", "new evidence"],
            methods: ["review", "form"],
            workProducts: ["Correction log"],
            humanDecisions: ["Confirm corrections"],
            prohibitedConclusions: ["Rewrite record silently"]),
        JobDocumentation(
            jobID: "JRN-14",
            persona: "Journalist",
            name: "Publication package",
            workflow: "Assemble cited package + receipt",
            requiredInputs: ["Verified claims", "quotes"],
            methods: ["work-product build"],
            workProducts: ["Publication package", "receipt"],
            humanDecisions: ["Approve package"],
            prohibitedConclusions: ["Include unverified fact"]),
        JobDocumentation(
            jobID: "IND-01",
            persona: "Individual",
            name: "Personal records",
            workflow: "Organize personal documents by category",
            requiredInputs: ["Personal documents"],
            methods: ["intake", "form"],
            workProducts: ["Records index"],
            humanDecisions: ["Confirm categories"],
            prohibitedConclusions: ["Expose sensitive data"]),
        JobDocumentation(
            jobID: "IND-02",
            persona: "Individual",
            name: "Official-document versions",
            workflow: "Track versions of official documents",
            requiredInputs: ["Documents"],
            methods: ["review", "table"],
            workProducts: ["Version history"],
            humanDecisions: ["Confirm current version"],
            prohibitedConclusions: ["Discard old version"]),
        JobDocumentation(
            jobID: "IND-03",
            persona: "Individual",
            name: "Career & education",
            workflow: "Compile career/education record",
            requiredInputs: ["Resumes", "certificates"],
            methods: ["form", "timeline"],
            workProducts: ["Career/education summary"],
            humanDecisions: ["Confirm entries"],
            prohibitedConclusions: ["Invent credentials"]),
        JobDocumentation(
            jobID: "IND-04",
            persona: "Individual",
            name: "Family records",
            workflow: "Organize family documents/relationships",
            requiredInputs: ["Family documents"],
            methods: ["relationship analysis"],
            workProducts: ["Family record"],
            humanDecisions: ["Confirm relationships"],
            prohibitedConclusions: ["Assert relationship w/o evidence"]),
        JobDocumentation(
            jobID: "IND-05",
            persona: "Individual",
            name: "Property",
            workflow: "Track property documents/ownership",
            requiredInputs: ["Deeds", "bills"],
            methods: ["form", "table"],
            workProducts: ["Property register"],
            humanDecisions: ["Confirm ownership"],
            prohibitedConclusions: ["Assert title"]),
        JobDocumentation(
            jobID: "IND-06",
            persona: "Individual",
            name: "Insurance",
            workflow: "Track policies/claims/renewals",
            requiredInputs: ["Policies", "correspondence"],
            methods: ["form", "table"],
            workProducts: ["Insurance register"],
            humanDecisions: ["Confirm renewals"],
            prohibitedConclusions: ["Auto-file a claim"]),
        JobDocumentation(
            jobID: "IND-07",
            persona: "Individual",
            name: "Health-record scope",
            workflow: "Organize health records under strict scope",
            requiredInputs: ["Health documents"],
            methods: ["review", "form"],
            workProducts: ["Health summary"],
            humanDecisions: ["Confirm scope"],
            prohibitedConclusions: ["Diagnose", "leak health data"]),
        JobDocumentation(
            jobID: "IND-08",
            persona: "Individual",
            name: "Applications & cases",
            workflow: "Track applications/cases and their documents",
            requiredInputs: ["Application documents"],
            methods: ["form", "workflow"],
            workProducts: ["Application tracker"],
            humanDecisions: ["Confirm submissions"],
            prohibitedConclusions: ["Submit on user's behalf"]),
        JobDocumentation(
            jobID: "IND-09",
            persona: "Individual",
            name: "Important dates & renewals",
            workflow: "Turn dated obligations into confirmed reminders",
            requiredInputs: ["Documents with dates"],
            methods: ["review", "form"],
            workProducts: ["Reminder list"],
            humanDecisions: ["Confirm each reminder"],
            prohibitedConclusions: ["Fire unconfirmed reminder"]),
        JobDocumentation(
            jobID: "IND-10",
            persona: "Individual",
            name: "Emergency binder (ICE)",
            workflow: "Assemble emergency document pack",
            requiredInputs: ["Key documents"],
            methods: ["work-product build"],
            workProducts: ["Emergency pack"],
            humanDecisions: ["Confirm pack"],
            prohibitedConclusions: ["Expose data insecurely"]),
        JobDocumentation(
            jobID: "IND-11",
            persona: "Individual",
            name: "Share safely (redacted)",
            workflow: "Share with verified redaction",
            requiredInputs: ["Documents", "recipients"],
            methods: ["review", "work-product build"],
            workProducts: ["Redacted export"],
            humanDecisions: ["Confirm redactions"],
            prohibitedConclusions: ["Leak redacted content"]),
        JobDocumentation(
            jobID: "IND-12",
            persona: "Individual",
            name: "Personal chronology",
            workflow: "Build a cited life timeline",
            requiredInputs: ["Events", "dates"],
            methods: ["timeline analysis"],
            workProducts: ["Personal chronology"],
            humanDecisions: ["Confirm inclusion"],
            prohibitedConclusions: ["Invent dates"]),
        JobDocumentation(
            jobID: "IND-13",
            persona: "Individual",
            name: "Legacy binder",
            workflow: "Assemble durable legacy archive + receipt",
            requiredInputs: ["Selected documents"],
            methods: ["work-product build"],
            workProducts: ["Legacy archive", "receipt"],
            humanDecisions: ["Approve archive"],
            prohibitedConclusions: ["Alter records silently"]),
        JobDocumentation(
            jobID: "LAW-01",
            persona: "Lawyer",
            name: "Matter intake",
            workflow: "Open matter; scope; parties; sources",
            requiredInputs: ["Matter facts", "scope", "sources"],
            methods: ["intake", "scope"],
            workProducts: ["Matter profile"],
            humanDecisions: ["Confirm scope"],
            prohibitedConclusions: ["Give legal advice"]),
        JobDocumentation(
            jobID: "LAW-02",
            persona: "Lawyer",
            name: "Parties & issues",
            workflow: "Identify parties and legal issues",
            requiredInputs: ["Parties", "issues"],
            methods: ["form", "review"],
            workProducts: ["Issue register"],
            humanDecisions: ["Confirm parties/issues"],
            prohibitedConclusions: ["Decide liability"]),
        JobDocumentation(
            jobID: "LAW-03",
            persona: "Lawyer",
            name: "Case chronology",
            workflow: "Build a cited statement-of-facts timeline",
            requiredInputs: ["Events", "dates"],
            methods: ["timeline analysis"],
            workProducts: ["Chronology / statement of facts"],
            humanDecisions: ["Confirm facts"],
            prohibitedConclusions: ["Assert disputed fact as settled"]),
        JobDocumentation(
            jobID: "LAW-04",
            persona: "Lawyer",
            name: "Fact–evidence matrix",
            workflow: "Map each fact to supporting/opposing evidence",
            requiredInputs: ["Claims", "evidence"],
            methods: ["matrix", "review"],
            workProducts: ["Fact-evidence matrix"],
            humanDecisions: ["Confirm mappings"],
            prohibitedConclusions: ["Average disputed facts"]),
        JobDocumentation(
            jobID: "LAW-05",
            persona: "Lawyer",
            name: "Witness profiles",
            workflow: "Per-witness summary + contradictions",
            requiredInputs: ["Transcripts", "testimony"],
            methods: ["review", "contradiction matrix"],
            workProducts: ["Witness summaries", "impeachment pack"],
            humanDecisions: ["Confirm profile"],
            prohibitedConclusions: ["Assert credibility verdict"]),
        JobDocumentation(
            jobID: "LAW-06",
            persona: "Lawyer",
            name: "Document coding",
            workflow: "Code documents by issue/relevance",
            requiredInputs: ["Documents", "codebook"],
            methods: ["form", "table"],
            workProducts: ["Coding log"],
            humanDecisions: ["Confirm codes"],
            prohibitedConclusions: ["Auto-exclude relevant docs"]),
        JobDocumentation(
            jobID: "LAW-07",
            persona: "Lawyer",
            name: "Privilege log",
            workflow: "Flag candidate-privileged documents for review",
            requiredInputs: ["Documents"],
            methods: ["review", "decision"],
            workProducts: ["Privilege log"],
            humanDecisions: ["Confirm privilege"],
            prohibitedConclusions: ["App marks privilege established"]),
        JobDocumentation(
            jobID: "LAW-08",
            persona: "Lawyer",
            name: "Obligations & clauses",
            workflow: "Compare clauses/obligations across documents",
            requiredInputs: ["Contracts"],
            methods: ["matrix", "calculation"],
            workProducts: ["Obligations schedule"],
            humanDecisions: ["Confirm comparisons"],
            prohibitedConclusions: ["Interpret contract as advice"]),
        JobDocumentation(
            jobID: "LAW-09",
            persona: "Lawyer",
            name: "Damages ledger",
            workflow: "Compute damages from source amounts",
            requiredInputs: ["Financial documents"],
            methods: ["calculation", "table"],
            workProducts: ["Damages ledger"],
            humanDecisions: ["Confirm figures"],
            prohibitedConclusions: ["Assert legal damages"]),
        JobDocumentation(
            jobID: "LAW-10",
            persona: "Lawyer",
            name: "Deadlines",
            workflow: "Track matter deadlines from documents",
            requiredInputs: ["Documents with dates"],
            methods: ["review", "form"],
            workProducts: ["Deadline calendar"],
            humanDecisions: ["Confirm each deadline"],
            prohibitedConclusions: ["Fire unconfirmed deadline"]),
        JobDocumentation(
            jobID: "LAW-11",
            persona: "Lawyer",
            name: "Deposition outline",
            workflow: "Draft deposition outline grounded in the record",
            requiredInputs: ["Transcripts", "Claims"],
            methods: ["review", "form"],
            workProducts: ["Deposition outline"],
            humanDecisions: ["Confirm outline"],
            prohibitedConclusions: ["Assert answers"]),
        JobDocumentation(
            jobID: "LAW-12",
            persona: "Lawyer",
            name: "Exhibit list & binder",
            workflow: "Assemble exhibit list/binder with index",
            requiredInputs: ["Selected documents"],
            methods: ["work-product build"],
            workProducts: ["Exhibit list", "binder"],
            humanDecisions: ["Confirm exhibits"],
            prohibitedConclusions: ["Alter an exhibit"]),
        JobDocumentation(
            jobID: "LAW-13",
            persona: "Lawyer",
            name: "Document production",
            workflow: "Produce cited export set with manifest + receipt",
            requiredInputs: ["Selected docs", "scope"],
            methods: ["work-product build"],
            workProducts: ["Production set", "receipt"],
            humanDecisions: ["Approve production"],
            prohibitedConclusions: ["Produce out-of-scope material"]),
        JobDocumentation(
            jobID: "LAW-14",
            persona: "Lawyer",
            name: "Redaction validation",
            workflow: "Verify redactions before disclosure",
            requiredInputs: ["Documents", "redactions"],
            methods: ["review", "work-product build"],
            workProducts: ["Redaction validation record"],
            humanDecisions: ["Confirm redactions"],
            prohibitedConclusions: ["Disclose redacted content"]),
        JobDocumentation(
            jobID: "RES-15",
            persona: "Researcher",
            name: "Ask the corpus",
            workflow: "Ask a question over the authorized corpus",
            requiredInputs: ["Question", "matter scope"],
            methods: ["retrieval", "evidence gate"],
            workProducts: ["Cited answer"],
            humanDecisions: ["Accept/refine answer"],
            prohibitedConclusions: ["Answer beyond the corpus"]),
        JobDocumentation(
            jobID: "RES-16",
            persona: "Researcher",
            name: "Method workbench",
            workflow: "Run structured methods over the matter",
            requiredInputs: ["Matter", "method choice"],
            methods: ["5W1H", "hypothesis matrix", "root cause"],
            workProducts: ["Method run record"],
            humanDecisions: ["Human review gates"],
            prohibitedConclusions: ["Auto-confirm findings"]),
        JobDocumentation(
            jobID: "RES-17",
            persona: "Researcher",
            name: "Causal analysis",
            workflow: "Trace why an event unfolded",
            requiredInputs: ["Event", "evidence"],
            methods: ["five whys", "fishbone"],
            workProducts: ["Causal chain record"],
            humanDecisions: ["Confirm root cause"],
            prohibitedConclusions: ["Unsupported causal leap"]),
        JobDocumentation(
            jobID: "RES-18",
            persona: "Researcher",
            name: "Errata register",
            workflow: "Track edition corrections to closure",
            requiredInputs: ["Identified errors"],
            methods: ["CAPA"],
            workProducts: ["Errata record"],
            humanDecisions: ["Close each erratum"],
            prohibitedConclusions: ["Silently rewrite the edition"]),
        JobDocumentation(
            jobID: "RES-19",
            persona: "Researcher",
            name: "Errata effectiveness review",
            workflow: "Verify a published correction resolved the issue",
            requiredInputs: ["Closed erratum"],
            methods: ["effectiveness check"],
            workProducts: ["Effectiveness record"],
            humanDecisions: ["Effectiveness decision"],
            prohibitedConclusions: ["Infer effectiveness from closure"]),
        JobDocumentation(
            jobID: "RES-20",
            persona: "Researcher",
            name: "Matter closure",
            workflow: "Close the research matter with sealed state",
            requiredInputs: ["Matter", "open items"],
            methods: ["closure review"],
            workProducts: ["Closure record"],
            humanDecisions: ["Confirm closure"],
            prohibitedConclusions: ["Destroy history on close"]),
        JobDocumentation(
            jobID: "JRN-15",
            persona: "Journalist",
            name: "Ask the story file",
            workflow: "Ask a question over the story sources",
            requiredInputs: ["Question", "story scope"],
            methods: ["retrieval", "evidence gate"],
            workProducts: ["Cited answer"],
            humanDecisions: ["Accept/refine answer"],
            prohibitedConclusions: ["Answer beyond sources"]),
        JobDocumentation(
            jobID: "JRN-16",
            persona: "Journalist",
            name: "Method workbench",
            workflow: "Run structured methods over the story",
            requiredInputs: ["Story", "method choice"],
            methods: ["5W1H", "hypothesis matrix"],
            workProducts: ["Method run record"],
            humanDecisions: ["Human review gates"],
            prohibitedConclusions: ["Auto-confirm findings"]),
        JobDocumentation(
            jobID: "JRN-17",
            persona: "Journalist",
            name: "Story data desk",
            workflow: "Build datasets over documents",
            requiredInputs: ["Documents", "fields"],
            methods: ["dataset", "transform"],
            workProducts: ["Cited dataset"],
            humanDecisions: ["Review derived values"],
            prohibitedConclusions: ["Fabricate a value"]),
        JobDocumentation(
            jobID: "JRN-18",
            persona: "Journalist",
            name: "Who's who resolution",
            workflow: "Unify names and aliases to one subject",
            requiredInputs: ["Candidate names", "mentions"],
            methods: ["review", "decision"],
            workProducts: ["Identity decision log"],
            humanDecisions: ["Confirm/reject merge"],
            prohibitedConclusions: ["Auto-merge without review"]),
        JobDocumentation(
            jobID: "JRN-19",
            persona: "Journalist",
            name: "Causal analysis",
            workflow: "Trace why events unfolded",
            requiredInputs: ["Event", "evidence"],
            methods: ["five whys", "fishbone"],
            workProducts: ["Causal chain record"],
            humanDecisions: ["Confirm root cause"],
            prohibitedConclusions: ["Unsupported causal leap"]),
        JobDocumentation(
            jobID: "JRN-20",
            persona: "Journalist",
            name: "Source-document vault",
            workflow: "Custody-tracked vault for source documents",
            requiredInputs: ["Documents"],
            methods: ["custody"],
            workProducts: ["Custody log"],
            humanDecisions: ["Confirm custody events"],
            prohibitedConclusions: ["Alter originals"]),
        JobDocumentation(
            jobID: "JRN-21",
            persona: "Journalist",
            name: "Correction actions",
            workflow: "Track corrective actions on published errors",
            requiredInputs: ["Published error"],
            methods: ["CAPA"],
            workProducts: ["Correction action record"],
            humanDecisions: ["Close each action"],
            prohibitedConclusions: ["Silently unpublish"]),
        JobDocumentation(
            jobID: "JRN-22",
            persona: "Journalist",
            name: "Correction effectiveness",
            workflow: "Verify a published correction resolved the error",
            requiredInputs: ["Closed correction"],
            methods: ["effectiveness check"],
            workProducts: ["Effectiveness record"],
            humanDecisions: ["Effectiveness decision"],
            prohibitedConclusions: ["Infer effectiveness from closure"]),
        JobDocumentation(
            jobID: "IND-14",
            persona: "Individual",
            name: "Ask my records",
            workflow: "Ask a question over your records",
            requiredInputs: ["Question"],
            methods: ["retrieval", "evidence gate"],
            workProducts: ["Cited answer"],
            humanDecisions: ["Accept/refine answer"],
            prohibitedConclusions: ["Answer beyond your records"]),
        JobDocumentation(
            jobID: "IND-15",
            persona: "Individual",
            name: "Guided methods",
            workflow: "Step-by-step structured methods",
            requiredInputs: ["Topic", "method choice"],
            methods: ["5W1H", "checklists"],
            workProducts: ["Method run record"],
            humanDecisions: ["Human review gates"],
            prohibitedConclusions: ["Auto-confirm findings"]),
        JobDocumentation(
            jobID: "IND-16",
            persona: "Individual",
            name: "Name & alias resolution",
            workflow: "Confirm two names are the same person/company",
            requiredInputs: ["Candidate names"],
            methods: ["review", "decision"],
            workProducts: ["Identity decision log"],
            humanDecisions: ["You confirm/reject"],
            prohibitedConclusions: ["Auto-merge without review"]),
        JobDocumentation(
            jobID: "IND-17",
            persona: "Individual",
            name: "Document reliability",
            workflow: "Assess how reliable a document/source is",
            requiredInputs: ["Document"],
            methods: ["reliability review"],
            workProducts: ["Reliability record"],
            humanDecisions: ["Confirm assessment"],
            prohibitedConclusions: ["Declare a document true"]),
        JobDocumentation(
            jobID: "IND-18",
            persona: "Individual",
            name: "Conflicts & gaps",
            workflow: "See where records disagree or are missing",
            requiredInputs: ["Records scope"],
            methods: ["contradiction", "gap"],
            workProducts: ["Conflict/gap register"],
            humanDecisions: ["Review each conflict"],
            prohibitedConclusions: ["Average conflicts away"]),
        JobDocumentation(
            jobID: "IND-19",
            persona: "Individual",
            name: "Why did this happen?",
            workflow: "Trace causes step by step",
            requiredInputs: ["Event", "records"],
            methods: ["five whys"],
            workProducts: ["Causal chain record"],
            humanDecisions: ["Confirm root cause"],
            prohibitedConclusions: ["Unsupported causal leap"]),
        JobDocumentation(
            jobID: "IND-20",
            persona: "Individual",
            name: "Fix-it list",
            workflow: "Track corrective actions to closure",
            requiredInputs: ["Identified problems"],
            methods: ["CAPA"],
            workProducts: ["Action record"],
            humanDecisions: ["Close each action"],
            prohibitedConclusions: ["Mark fixed without doing it"]),
        JobDocumentation(
            jobID: "IND-21",
            persona: "Individual",
            name: "Did the fix work?",
            workflow: "Verify a completed fix resolved the problem",
            requiredInputs: ["Closed action"],
            methods: ["effectiveness check"],
            workProducts: ["Effectiveness record"],
            humanDecisions: ["You decide effectiveness"],
            prohibitedConclusions: ["Infer effectiveness from closure"]),
        JobDocumentation(
            jobID: "IND-22",
            persona: "Individual",
            name: "Document vault",
            workflow: "Custody-tracked vault for originals",
            requiredInputs: ["Documents"],
            methods: ["custody"],
            workProducts: ["Custody log"],
            humanDecisions: ["Confirm custody events"],
            prohibitedConclusions: ["Alter originals"]),
        JobDocumentation(
            jobID: "IND-23",
            persona: "Individual",
            name: "Close a matter",
            workflow: "Close a personal matter with sealed state",
            requiredInputs: ["Matter", "open items"],
            methods: ["closure review"],
            workProducts: ["Closure record"],
            humanDecisions: ["Confirm closure"],
            prohibitedConclusions: ["Destroy history on close"]),
        JobDocumentation(
            jobID: "LAW-15",
            persona: "Lawyer",
            name: "Ask the case file",
            workflow: "Ask a question over the matter record",
            requiredInputs: ["Question", "matter scope"],
            methods: ["retrieval", "evidence gate"],
            workProducts: ["Cited answer"],
            humanDecisions: ["Accept/refine answer"],
            prohibitedConclusions: ["Answer beyond the record"]),
        JobDocumentation(
            jobID: "LAW-16",
            persona: "Lawyer",
            name: "Method workbench",
            workflow: "Run structured methods over the matter",
            requiredInputs: ["Matter", "method choice"],
            methods: ["5W1H", "hypothesis matrix"],
            workProducts: ["Method run record"],
            humanDecisions: ["Human review gates"],
            prohibitedConclusions: ["Auto-confirm findings"]),
        JobDocumentation(
            jobID: "LAW-17",
            persona: "Lawyer",
            name: "Party & alias resolution",
            workflow: "Unify party names and aliases",
            requiredInputs: ["Candidate names", "mentions"],
            methods: ["review", "decision"],
            workProducts: ["Identity decision log"],
            humanDecisions: ["Confirm/reject merge"],
            prohibitedConclusions: ["Auto-merge without review"]),
        JobDocumentation(
            jobID: "LAW-18",
            persona: "Lawyer",
            name: "Source reliability desk",
            workflow: "Assess reliability/independence of sources",
            requiredInputs: ["Sources"],
            methods: ["reliability review"],
            workProducts: ["Reliability record"],
            humanDecisions: ["Confirm assessment"],
            prohibitedConclusions: ["Declare a source true"]),
        JobDocumentation(
            jobID: "LAW-19",
            persona: "Lawyer",
            name: "Causation analysis",
            workflow: "Trace causation step by step",
            requiredInputs: ["Event", "record"],
            methods: ["five whys", "fishbone"],
            workProducts: ["Causal chain record"],
            humanDecisions: ["Confirm root cause"],
            prohibitedConclusions: ["Assert legal causation as fact"]),
        JobDocumentation(
            jobID: "LAW-20",
            persona: "Lawyer",
            name: "Remediation register",
            workflow: "Track remediation/undertakings to closure",
            requiredInputs: ["Identified issues"],
            methods: ["CAPA"],
            workProducts: ["Remediation record"],
            humanDecisions: ["Close each action"],
            prohibitedConclusions: ["Mark remediated without evidence"]),
        JobDocumentation(
            jobID: "LAW-21",
            persona: "Lawyer",
            name: "Remediation effectiveness",
            workflow: "Verify a remediation resolved the issue",
            requiredInputs: ["Closed remediation"],
            methods: ["effectiveness check"],
            workProducts: ["Effectiveness record"],
            humanDecisions: ["Effectiveness decision"],
            prohibitedConclusions: ["Infer effectiveness from closure"]),
        JobDocumentation(
            jobID: "LAW-22",
            persona: "Lawyer",
            name: "Matter closure & reopen",
            workflow: "Close the matter; reopen preserves history",
            requiredInputs: ["Matter", "open items"],
            methods: ["closure review"],
            workProducts: ["Closure record"],
            humanDecisions: ["Confirm closure"],
            prohibitedConclusions: ["Destroy history on close"]),
    ]
}
