//
//  LegalNotice.swift
//  Kalsmritikosh
//
//  Central, single-source legal/accuracy declarations. Kalsmritikosh
//  reconstructs the most evidence-supported version of events from a finite
//  document set — it is an aid, not an authority. Every AI-assisted output
//  must carry a clear "may be wrong — verify against the cited sources"
//  declaration, and nothing here is legal/financial/professional advice.
//
//  Surfaces that use these strings: the per-answer QualityStrip, the Ask
//  entry screen, and every exported report/dossier.
//

import Foundation

public enum LegalNotice {
    /// Short line shown under every answer (space-constrained UI).
    public static let answerFooter =
        "AI-assisted answer — it can be incomplete or wrong. Verify every fact against the cited sources before you rely on it. Not legal, financial, or professional advice."

    /// One-liner for the Ask entry / empty state.
    public static let askEntry =
        "Answers are reconstructed from your documents and can contain mistakes — always check them against the cited sources."

    /// Full disclaimer block prepended to any exported report or dossier
    /// (the artifacts that may be attached to a brief, filing, or story).
    public static let reportDisclaimer = """
    > **Disclaimer — read before relying on this document.**
    > This report was generated by Kalsmritikosh, an automated evidence-reconstruction
    > tool. It may contain errors, omissions, or misinterpretations, and some items are
    > inferred rather than directly proven. Every statement must be independently verified
    > against the cited source documents. This is **not** legal, financial, or professional
    > advice and must not be relied upon as the sole basis for any decision or filing.
    """

    // MARK: - Settings "Legal & Privacy" copy

    public static let disclaimerHeadline = "Kalsmritikosh is an evidence aid, not an authority."

    public static let accuracyStatement = """
    Kalsmritikosh reconstructs the most evidence-supported version of events from the \
    documents you give it. It uses AI to interpret and explain that evidence, so its \
    answers, timelines, and reports can be incomplete or wrong, and some items are \
    inferred rather than directly proven. Always verify every fact against the cited \
    sources. Nothing it produces is legal, financial, medical, or other professional \
    advice, and it must not be the sole basis for any decision, filing, or publication. \
    You remain fully responsible for how you use its output.
    """

    public static let privacyStatement = """
    Private by design. Your documents, the extracted ledger, and your questions stay on \
    this device — they are not sent to any server and there is no analytics or telemetry. \
    A cloud AI provider is used only if you explicitly enable it in Privacy settings; \
    otherwise all processing is on-device (Apple’s on-device model, or a local Ollama you \
    run yourself). You can delete everything by removing the app’s data folder.
    """

    public static let termsStatement = """
    Provided “as is”, without warranty of any kind. To the maximum extent permitted by \
    law, the developer is not liable for any loss or damage arising from use of the app or \
    reliance on its output. You confirm you have the legal right to ingest and analyse the \
    documents you add, and that you will use the app lawfully — not for unlawful \
    surveillance, harassment, or to violate anyone’s privacy or confidentiality \
    (including legally privileged material you are not entitled to review).
    """

    public static let thirdPartyStatement = """
    Built with Apple frameworks (Vision, Speech, Natural Language, Core ML). Semantic \
    search uses an on-device BGE embedding/reranker model. Optional local generation uses \
    Ollama, and optional cloud generation uses the provider you configure. Respective \
    licences and terms apply.
    """

    /// Shown once in Settings so the operator knows this is template copy.
    public static let counselNote = """
    These notices are a good-faith starting point, not a substitute for legal review. \
    Have qualified counsel adapt the Terms, Privacy Policy, and disclaimers to your \
    jurisdiction and distribution before public or commercial release.
    """
}
