#!/usr/bin/env bash
# P5-U1 (I-8) — generate SCOREBOARD.md: one view over every claim on every
# surface, with its proof and its gate. GENERATED — edit the registries
# (CLAIMS.md, CLAIMS_APP.md), never this file.
set -uo pipefail
cd "$(dirname "$0")/.."
OUT="SCOREBOARD.md"
{
echo "# SCOREBOARD — every public claim, every surface, one table (GENERATED)"
echo
echo "Generated by scripts/generate-scoreboard.sh. The gates: the site leg is"
echo "scripts/check-claims.sh (data-claim id gate, both directions); the in-app"
echo "and App Store legs are ci/guards/app-claims-coverage.sh. CI fails on any"
echo "drift between copy and registry, on any surface."
echo
echo "| Surface | Claim ID | Fragment | Proof / gate |"
echo "|---|---|---|---|"
grep '^| `' CLAIMS.md | sed -E 's/^\| `([^`]+)` \| `([^`]*)` \| (.*) \|$/| site | \1 | \2 | \3 |/'
grep -E '^\| app\.' CLAIMS_APP.md | sed -E 's/^\| ([^ |]+) \| `([^`]*)` \| (.*) \|$/| in-app | \1 | \2 | app-claims-coverage.sh → \3 |/'
grep -E '^\| asc\.' CLAIMS_APP.md | sed -E 's/^\| ([^ |]+) \| `([^`]*)` \| (.*) \|$/| App Store | \1 | \2 | app-claims-coverage.sh → \3 |/'
echo
echo "## Per-persona status (I-8 — generated by the gold-wall witness run)"
echo
echo "See [release/PERSONA_STATUS.generated.md](release/PERSONA_STATUS.generated.md) —"
echo "every wall row per persona archive with its measured verdict; the wall"
echo "suite is the CI gate (a breach turns build-and-test red), and the"
echo "generator refuses to render from a red run."
echo
echo "## Twin-disagreement rate (advisory quality signal, per component)"
echo
echo "The verification twins are checkers, never writers: their verdicts land"
echo "as advisory review rows and log counters, excluded from every sealed"
echo "envelope. The rates are measured on the live ledger, per reviewer:"
echo
echo '| Component | Where measured |'
echo '|---|---|'
echo '| Entity plausibility twin | fact_reviews rows, reviewer `twin.entity` (flag ÷ scanned) |'
echo '| Event record twin | fact_reviews rows, reviewer `twin.event` (flag ÷ examined) |'
echo '| Story placement twin | fact_reviews rows, reviewer `twin.placement` (flag ÷ artifacts) |'
echo '| Compose twin | log counters `twin.compose` (disagreed ÷ run) |'
echo
echo "A rising rate is a RULE-DEFECT signal for that component — findings feed"
echo "review, never auto-tuning."
echo
echo "## Break-budgets (I-9) — adversarial groups, every break a permanent case"
echo
echo '| Promise group | Budget | Suite |'
echo '|---|---|---|'
echo '| Defeat the abstention | 5 cases | KalsmritikoshTests/BreakBudgetTests (abstention group) |'
echo '| Smuggle a digit | 5 cases | KalsmritikoshTests/BreakBudgetTests (digit group) |'
echo '| Mis-anchor a milestone | 5 cases | KalsmritikoshTests/BreakBudgetTests (anchor group) |'
echo
echo "A group is CLOSED only when its budget is spent with no open break; any"
echo "future break joins the suite permanently before the fix ships."
} > "$OUT"
echo "wrote $OUT"
