#!/usr/bin/env bash
# P5-U1 (I-8, the Status column) — render the gold wall's own verdicts into
# the generated per-persona status table. The WALL is the witness runner and
# the CI gate (any threshold breach = suite red); this script renders what it
# measured. Usage:
#   scripts/generate-persona-status.sh [wall-log]     # default: runs the wall
set -uo pipefail
cd "$(dirname "$0")/.."
LOG="${1:-}"
if [ -z "$LOG" ]; then
  LOG=$(mktemp /tmp/gold-wall.XXXX.log)
  xcodebuild test -project Kalsmritikosh.xcodeproj -scheme Kalsmritikosh \
    -destination 'platform=macOS' -only-testing:KalsmritikoshTests/GoldWallTests \
    -parallel-testing-enabled NO > "$LOG" 2>&1 || { echo "WALL RED — no status table on a red wall"; exit 1; }
fi
grep -q "TEST EXECUTE SUCCEEDED\|Test run.*passed" "$LOG" || { echo "::error::wall log carries no green verdict"; exit 1; }
OUT="release/PERSONA_STATUS.generated.md"
{
echo "# Persona status — GENERATED by the gold-wall witness run"
echo
echo "The wall's absolute thresholds: refusal/abstention 1.0 on unanswerable"
echo "rows · hallucination 0 (tripwires, both directions, plus the global"
echo "'Reported:' ban) · false-not-found 0 on answerable rows. The suite is"
echo "the CI gate — any breach turns build-and-test red. This table renders"
echo "what the run measured; edit nothing here."
echo
echo "| Persona archive | Question | Answered/refused | Status |"
echo "|---|---|---|---|"
grep "GOLD-WALL" "$LOG" | python3 -c "
import sys, re
rows = set()
for line in sys.stdin:
    m = re.search(r\"GOLD-WALL (\\w+): '(.*)' → refused=(\\w+)\", line)
    if m: rows.add((m.group(1), m.group(2), m.group(3)))
for a, q, r in sorted(rows):
    print(f'| {a} | {q} | refused={r} | PASS (thresholds held) |')"
echo
echo "Suite verdict: GREEN (all rows, all archives — a red wall refuses to"
echo "generate this file)."
} > "$OUT"
echo "wrote $OUT"
