#!/usr/bin/env python3
"""
module-matrix.py — generate MODULE_MATRIX.md from the KnowledgeModule enum.

WHY GENERATED. The owner's requirement is that every new capability ships behind
its own switch "so each can live without any risk". That promise is only real if
you can SEE, per module, that a gate actually exists in the code. A
hand-maintained table would claim gates that were never wired — the same
absence-rendered-as-verification failure this project keeps closing. So the
matrix is derived from the enum, and the WIRED column is derived from a grep for
`isEnabled(.case)` in non-test source.

A module that appears in the switchboard with no `isEnabled` call anywhere is
reported as NOT WIRED: its switch is decorative, and flipping it would change
nothing. That is the single most useful column here.

Usage:  python3 scripts/module-matrix.py [--out MODULE_MATRIX.md]
"""

import argparse
import io
import os
import re
import sys
from collections import OrderedDict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENUM = os.path.join(REPO, "Kalsmritikosh", "Knowledge", "Modules", "KnowledgeModule.swift")
SRC = os.path.join(REPO, "Kalsmritikosh")
TESTS = os.path.join(REPO, "KalsmritikoshTests")


def enum_cases(text):
    """Declaration order, which is the order the switchboard presents."""
    body = text.split("public enum KnowledgeModule", 1)[1]
    body = body.split("public var id:", 1)[0]
    return [m.group(1) for m in re.finditer(r"^\s*case\s+([a-zA-Z][A-Za-z0-9_]*)", body, re.M)]


def switch_map(text, prop):
    """Map case -> returned string for a `public var <prop>` switch."""
    i = text.find("public var %s:" % prop)
    if i < 0:
        return {}
    seg = text[i:]
    # end at the next `public var` / `public func` / `fileprivate`
    ends = [seg.find("\n    public var ", 10), seg.find("\n    public func ", 10),
            seg.find("\n    fileprivate ", 10)]
    ends = [e for e in ends if e > 0]
    if ends:
        seg = seg[:min(ends)]
    out = {}
    for m in re.finditer(r"case\s+((?:\.[a-zA-Z0-9_]+\s*,?\s*)+):\s*return\s+\"((?:[^\"\\]|\\.)*)\"", seg):
        value = m.group(2)
        for c in re.findall(r"\.([a-zA-Z0-9_]+)", m.group(1)):
            out[c] = value
    return out


def case_list_for(text, prop, needle="return true"):
    """Cases appearing in a boolean switch branch that yields `needle`."""
    i = text.find("public var %s:" % prop)
    if i < 0:
        return set()
    seg = text[i:i + 2500]
    out = set()
    for m in re.finditer(r"case\s+((?:\.[a-zA-Z0-9_]+\s*,?\s*\n?\s*)+):\s*\n?\s*" + re.escape(needle), seg):
        out.update(re.findall(r"\.([a-zA-Z0-9_]+)", m.group(1)))
    return out


def swift_files(root):
    for d, _, fs in os.walk(root):
        for f in fs:
            if f.endswith(".swift"):
                yield os.path.join(d, f)


def wiring(cases):
    """case -> [file:line] where `isEnabled(.case)` appears in non-test source."""
    hits = {c: [] for c in cases}
    for path in swift_files(SRC):
        if path == ENUM:
            continue
        try:
            lines = io.open(path, encoding="utf-8", errors="ignore").read().split("\n")
        except OSError:
            continue
        rel = os.path.relpath(path, REPO)
        for n, line in enumerate(lines, 1):
            t = line.strip()
            if t.startswith("//"):
                continue
            for c in cases:
                if "isEnabled(.%s)" % c in line:
                    hits[c].append("%s:%d" % (rel, n))
    return hits


def test_refs(cases):
    hits = {c: 0 for c in cases}
    if not os.path.isdir(TESTS):
        return hits
    for path in swift_files(TESTS):
        try:
            text = io.open(path, encoding="utf-8", errors="ignore").read()
        except OSError:
            continue
        for c in cases:
            if re.search(r"\.%s\b" % re.escape(c), text):
                hits[c] += 1
    return hits


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="MODULE_MATRIX.md")
    args = ap.parse_args()

    text = io.open(ENUM, encoding="utf-8", errors="ignore").read()
    cases = enum_cases(text)
    titles = switch_map(text, "title")
    groups = switch_map(text, "group")
    implemented = case_list_for(text, "implemented")
    requires_ai = case_list_for(text, "requiresAI")
    default_off = case_list_for(text, "defaultEnabled", "return false")
    wired = wiring(cases)
    tested = test_refs(cases)

    by_group = OrderedDict()
    for c in cases:
        by_group.setdefault(groups.get(c, "—"), []).append(c)

    unwired = [c for c in cases if c in implemented and not wired[c]]

    o = []
    o.append("# MODULE_MATRIX — every switchable capability\n")
    o.append("Generated by `python3 scripts/module-matrix.py`. Do not hand-edit.\n")
    o.append("\nThe owner's requirement is that each capability ships behind its own switch\n"
             "so it can live — or be turned off — without risk to the rest. This table is\n"
             "derived from the `KnowledgeModule` enum, and the **Wired** column is derived\n"
             "from a grep for `isEnabled(.case)` in non-test source.\n")
    o.append("\n> **The column that matters is Wired.** A module listed in the switchboard\n"
             "> with no `isEnabled` call anywhere has a DECORATIVE switch: flipping it\n"
             "> changes nothing. A hand-written table would have claimed the gate existed.\n")

    o.append("\n## Summary\n")
    o.append("| metric | count |")
    o.append("|---|---|")
    o.append("| modules declared | %d |" % len(cases))
    o.append("| implemented | %d |" % len(implemented))
    o.append("| **implemented but NOT WIRED** | **%d** |" % len(unwired))
    o.append("| default OFF (opt-in) | %d |" % len(default_off))
    o.append("| require the on-device model | %d |" % len(requires_ai))
    o.append("| referenced by a test | %d |" % sum(1 for c in cases if tested[c]))

    if unwired:
        o.append("\n## ⚠️ Decorative switches — implemented, but no gate found (%d)\n" % len(unwired))
        o.append("| module | title |")
        o.append("|---|---|")
        for c in unwired:
            o.append("| `%s` | %s |" % (c, titles.get(c, "")))
        o.append("\nEither gate the code path with `KnowledgeModuleFlags.isEnabled(.<case>)`,\n"
                 "or set `implemented = false` until it is wired.\n")

    for group, members in by_group.items():
        o.append("\n## %s\n" % group)
        o.append("| module | default | AI? | wired at | tests |")
        o.append("|---|---|---|---|---|")
        for c in members:
            if c not in implemented:
                default = "unimplemented"
            else:
                default = "OFF (opt-in)" if c in default_off else "ON"
            where = wired[c][0] if wired[c] else "**not wired**"
            if len(wired[c]) > 1:
                where += " (+%d more)" % (len(wired[c]) - 1)
            o.append("| `%s` — %s | %s | %s | %s | %d |" % (
                c, titles.get(c, ""), default,
                "yes" if c in requires_ai else "—", where, tested[c]))

    o.append("\n## How to add one\n")
    o.append("1. add a `case` to `KnowledgeModule` with title / detail / group;\n"
             "2. gate the code path with `KnowledgeModuleFlags.isEnabled(.yourCase)`;\n"
             "3. it auto-appears in Settings → Modules and in this matrix.\n")
    o.append("\nGate ONCE, as low as possible. The Phase-1 failure recorder is gated inside\n"
             "`DerivationFailureRepository.record` rather than at its twelve call sites, so\n"
             "the switch cannot be honoured in some paths and forgotten in others.\n")
    o.append("\n## What must NOT become a switch\n")
    o.append("A correctness fix is not a module. The entity-insert cascade (P1.1) is gated\n"
             "by `strictDerivation`, but BOTH of its states are non-corrupting — the switch\n"
             "chooses HOW to degrade (abort the file, or skip only the dependent step),\n"
             "never whether to write wrong data. Offering the old swallow-and-continue\n"
             "behaviour as an option would be offering ledger corruption as a preference.\n")

    io.open(os.path.join(REPO, args.out), "w", encoding="utf-8").write("\n".join(o) + "\n")
    print("modules: %d declared, %d implemented, %d NOT WIRED" % (
        len(cases), len(implemented), len(unwired)))
    for c in unwired:
        print("   not wired: %s" % c)
    print("\nwrote %s" % args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
