//
//  CrossDocumentMatrix.swift
//  Kalsmritikosh
//
//  "Ask across every document at once" — the cross-source review matrix
//  (the capability lawyers/journalists reach for: what does EACH document say
//  about this?). Done the evidence-ledger way: DETERMINISTIC and verbatim — for
//  a query, the best-matching passage from each source is shown with its
//  citation, so nothing is summarized-away or hallucinated. Pure FTS + grouping;
//  no model, so it works fully on-device without a reasoning model.
//

import Foundation

/// One row of the matrix: a source document and its best verbatim passage.
public struct CrossDocMatrixRow: Identifiable, Sendable, Hashable {
    public var id: KnowledgeObject.ID { objectID }
    public let objectID: KnowledgeObject.ID
    public let filename: String
    public let url: URL?
    public let date: Date?
    public let passage: String
    public let ordinal: Int
    public let pageNumber: Int?

    public init(
        objectID: KnowledgeObject.ID, filename: String, url: URL?, date: Date?,
        passage: String, ordinal: Int, pageNumber: Int?
    ) {
        self.objectID = objectID; self.filename = filename; self.url = url
        self.date = date; self.passage = passage; self.ordinal = ordinal
        self.pageNumber = pageNumber
    }
}

/// Pure helpers for turning a rank-ordered chunk list into a per-source matrix.
public enum CrossDocumentMatrix {

    /// From an FTS-rank-ordered chunk list, keep the FIRST (best) chunk per
    /// source document, preserving rank order, up to `maxSources`.
    public static func pickBestPerSource(_ chunks: [Chunk], maxSources: Int = 40) -> [Chunk] {
        var seen = Set<KnowledgeObject.ID>()
        var out: [Chunk] = []
        for c in chunks {
            guard seen.insert(c.objectID).inserted else { continue }
            out.append(c)
            if out.count >= maxSources { break }
        }
        return out
    }

    /// A readable excerpt centered on the first query term found in `text`
    /// (case-insensitive), falling back to the leading text. Verbatim — only
    /// trimmed and windowed, never paraphrased.
    public static func snippet(_ text: String, query: String, maxLen: Int = 320) -> String {
        let clean = text.replacingOccurrences(of: "\n", with: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard clean.count > maxLen else { return clean }
        let lower = clean.lowercased()
        // First meaningful query term that occurs in the passage.
        let terms = query.lowercased()
            .split { !$0.isLetter && !$0.isNumber }
            .map(String.init)
            .filter { $0.count >= 3 }
        var window = clean.startIndex..<clean.index(clean.startIndex, offsetBy: maxLen)
        for term in terms {
            if let r = lower.range(of: term) {
                let pad = 60
                let startOffset = Swift.max(0, lower.distance(from: lower.startIndex, to: r.lowerBound) - pad)
                let start = clean.index(clean.startIndex, offsetBy: startOffset)
                let end = clean.index(start, offsetBy: maxLen, limitedBy: clean.endIndex) ?? clean.endIndex
                window = start..<end
                break
            }
        }
        var out = String(clean[window]).trimmingCharacters(in: .whitespaces)
        if window.lowerBound > clean.startIndex { out = "…" + out }
        if window.upperBound < clean.endIndex { out += "…" }
        return out
    }

    /// Render the matrix as a cited GitHub-flavored markdown table for export.
    public static func markdown(query: String, rows: [CrossDocMatrixRow]) -> String {
        var md = "# Cross-document matrix\n\n"
        md += "**Question:** \(query)\n\n"
        md += "_Each row is one source document and its best-matching verbatim passage. "
        md += "Deterministic full-text match — nothing is summarized or inferred._\n\n"
        md += "| # | Document | Date | Passage |\n|---|---|---|---|\n"
        let iso = ISO8601DateFormatter()
        iso.formatOptions = [.withFullDate]
        for (i, r) in rows.enumerated() {
            let date = r.date.map { iso.string(from: $0) } ?? "—"
            let page = r.pageNumber.map { " (p.\($0))" } ?? ""
            let passage = r.passage.replacingOccurrences(of: "|", with: "\\|")
            md += "| \(i + 1) | \(r.filename)\(page) | \(date) | \(passage) |\n"
        }
        md += "\n_\(rows.count) source(s) matched. Generated by Kalsmritikosh._\n"
        return md
    }
}
