//
//  TopicRetriever.swift
//  Kalsmritikosh
//
//  HISTORY Phase B.4 — wraps the community detector + summarizer
//  output into a retrieval layer the brain can consult. Given a
//  question, returns:
//    - The community whose top entities overlap the question most
//    - That community's summary + member list
//    - The events generated by KOs that mention community members
//
//  Used by HybridRetriever (when wired) as a high-priority pre-pass
//  for narrative-shaped questions ("tell me the story of X", "what
//  happened with Y"), and by the Phase D narrative composer to
//  scope a chapter to a single topic.
//

import Foundation
import OSLog

public struct TopicMatch: Sendable {
    public let communityID: UUID
    public let title: String
    public let summary: String
    public let memberCount: Int
    public let topEntityIDs: [Entity.ID]
    /// How many of the question's entity hints showed up in this
    /// community (used by callers to decide whether the match is
    /// strong enough to act on).
    public let hintOverlap: Int
}

public actor TopicRetriever {
    private let database: Database
    private let entities: EntitiesRepository

    public init(database: Database, entities: EntitiesRepository) {
        self.database = database
        self.entities = entities
    }

    /// Find the community whose top entities best overlap the
    /// resolved entity hints. Returns nil when no community has at
    /// least one matching entity OR no summaries have been written
    /// yet (B.3 hasn't run).
    public func bestMatch(forEntityHints hints: [String]) async -> TopicMatch? {
        guard !hints.isEmpty else { return nil }

        // Resolve hints to entity ids by exact / normalized match.
        var hintEntityIDs: Set<UUID> = []
        for hint in hints {
            guard let rows = try? await entities.find(byValue: hint, limit: 8) else { continue }
            for entity in rows {
                hintEntityIDs.insert(entity.id)
            }
        }
        guard !hintEntityIDs.isEmpty else { return nil }

        // For each candidate community, count how many of its
        // members overlap with the hint set. Pick the community
        // with the highest overlap.
        let placeholders = hintEntityIDs.map { _ in "?" }.joined(separator: ",")
        let rows: [SQLRow]
        do {
            rows = try await database.query("""
            SELECT ec.community_id, COUNT(DISTINCT ec.entity_id) AS overlap_count
            FROM entity_communities ec
            WHERE ec.entity_id IN (\(placeholders))
              AND ec.level = 0
            GROUP BY ec.community_id
            ORDER BY overlap_count DESC, ec.community_id ASC
            LIMIT 1;
            """, hintEntityIDs.map { .uuid($0) })
        } catch {
            AtlasLog.knowledge.error("TopicRetriever: bestMatch query failed — \(String(describing: error), privacy: .public)")
            return nil
        }
        guard let row = rows.first,
              let communityID = row.uuid(0),
              let overlap = row.int(1), overlap > 0
        else { return nil }

        // Hydrate the summary row.
        return await fetch(communityID: communityID, hintOverlap: Int(overlap))
    }

    /// Direct lookup by community id (used by callers that already
    /// resolved a community via dossier / library navigation).
    public func fetch(communityID: UUID, hintOverlap: Int = 0) async -> TopicMatch? {
        let rows: [SQLRow]
        do {
            rows = try await database.query("""
            SELECT community_id, title, summary, member_count, top_entity_ids_json
            FROM community_summaries
            WHERE community_id = ? AND level = 0
            LIMIT 1;
            """, [.uuid(communityID)])
        } catch {
            AtlasLog.knowledge.error("TopicRetriever: fetch query failed — \(String(describing: error), privacy: .public)")
            return nil
        }
        guard let row = rows.first,
              let id = row.uuid(0),
              let title = row.string(1),
              let summary = row.string(2),
              let count = row.int(3) else { return nil }
        let topJSON = row.string(4) ?? "[]"
        let topIDs = (try? JSONDecoder().decode([UUID].self, from: Data(topJSON.utf8))) ?? []
        return TopicMatch(
            communityID: id,
            title: title,
            summary: summary,
            memberCount: Int(count),
            topEntityIDs: topIDs,
            hintOverlap: hintOverlap
        )
    }

    /// List recent topics ordered by member count. Used by the
    /// future LibraryView (Phase E.2) to render a topic tree.
    public func listTopics(limit: Int = 50) async -> [TopicMatch] {
        let rows: [SQLRow]
        do {
            rows = try await database.query("""
            SELECT community_id, title, summary, member_count, top_entity_ids_json
            FROM community_summaries
            WHERE level = 0
            ORDER BY member_count DESC
            LIMIT ?;
            """, [.integer(Int64(limit))])
        } catch {
            return []
        }
        return rows.compactMap { row -> TopicMatch? in
            guard let id = row.uuid(0),
                  let title = row.string(1),
                  let summary = row.string(2),
                  let count = row.int(3) else { return nil }
            let topJSON = row.string(4) ?? "[]"
            let topIDs = (try? JSONDecoder().decode([UUID].self, from: Data(topJSON.utf8))) ?? []
            return TopicMatch(
                communityID: id,
                title: title,
                summary: summary,
                memberCount: Int(count),
                topEntityIDs: topIDs,
                hintOverlap: 0
            )
        }
    }
}
